server:
  port: 8762
spring:
  application:
    name: eureka-client
#defaultZone: http://peer1:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #访问http://localhost:8762/actuator/hystrix.stream，如果不添加，则无法进行访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



